# Generated by Django 4.1.2 on 2022-10-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khata',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
