# Generated by Django 4.1.2 on 2022-10-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_khata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khata',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
