# Generated by Django 4.1.2 on 2022-10-09 00:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_khata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('month', core.models.MonthField(help_text='electricity bill', verbose_name='Month Value')),
                ('year', models.IntegerField(default=2022)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=25000)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('month', core.models.MonthField(help_text='water bill', verbose_name='Month Value')),
                ('year', models.IntegerField(default=2022)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
