# Generated by Django 4.1.2 on 2022-10-09 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_remove_electricitybill_year_remove_waterbill_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khata',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='khata', to=settings.AUTH_USER_MODEL),
        ),
    ]
