# Generated by Django 4.1.2 on 2022-10-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_khata_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='due_date',
            field=models.DateField(blank=True, help_text='due date', null=True),
        ),
    ]
