# Generated by Django 4.1.2 on 2022-10-10 18:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_electricitybill_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('month', core.models.MonthField(help_text='water bill', verbose_name='Month Value')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='khata',
            name='date',
            field=models.DateField(blank=True, help_text='keep the current billing month', null=True),
        ),
    ]
